if (typeof utils !== 'object' || !utils) utils = {};
if (typeof utils.keys !== 'object' || !utils.keys) utils.keys = {};

/**
 * Keyboard keyChar Dictionary with keyChar as keys and value is an array-list with possible names.
 *
 * @package utils.keys
 * @author Nijiko Yonskai <nijikokun@gmail.com>
 * @year 2012
 * @license AOL <http://aol.nexua.org>
 */
utils.keys.dictionary = {
  8:    [ 'backspace' ],
  9:    [ 'tab' ],
  13:   [ 'enter', 'return' ],
  16:   [ 'shift' ],
  17:   [ 'ctrl', 'control' ],
  18:   [ 'alt', 'option' ],
  19:   [ 'pause', 'break' ],
  20:   [ 'caps', 'caps lock' ],
  27:   [ 'escape' ],
  32:   [ 'space', 'space bar', ' '],
  33:   [ 'page up', 'pup' ],
  34:   [ 'page down', 'pdown' ],
  35:   [ 'end' ],
  36:   [ 'home' ],
  37:   [ 'left', 'left arrow', 'west' ],
  38:   [ 'up',  'up arrow', 'north' ],
  39:   [ 'right', 'right arrow', 'east' ],
  40:   [ 'down', 'down arrow', 'south' ],
  45:   [ 'insert', 'ins' ],
  46:   [ 'delete', 'del' ],
  48:   [ 0, '0', 'zero' ],
  49:   [ 1, '1', 'one' ],
  50:   [ 2, '2', 'two' ],
  51:   [ 3, '3', 'three' ],
  52:   [ 4, '4', 'four' ],
  53:   [ 5, '5', 'five' ],
  54:   [ 6, '6', 'six' ],
  55:   [ 7, '7', 'seven' ],
  56:   [ 8, '8', 'eight' ],
  57:   [ 9, '9', 'nine' ],
  65:   [ 'a' ],
  66:   [ 'b' ],
  67:   [ 'c' ],
  68:   [ 'd' ],
  69:   [ 'e' ],
  70:   [ 'f' ],
  71:   [ 'g' ],
  72:   [ 'h' ],
  73:   [ 'i' ],
  74:   [ 'j' ],
  75:   [ 'k' ],
  76:   [ 'l' ],
  77:   [ 'm' ],
  78:   [ 'n' ],
  79:   [ 'o' ],
  80:   [ 'p' ],
  81:   [ 'q' ],
  82:   [ 'r' ],
  83:   [ 's' ],
  84:   [ 't' ],
  85:   [ 'u' ],
  86:   [ 'v' ],
  87:   [ 'w' ],
  88:   [ 'x' ],
  89:   [ 'y' ],
  90:   [ 'z' ],
  91:   [ 'left command', 'lc', 'left meta', 'lm', 'left window key', 'lwk' ],
  92:   [ 'right command', 'rc', 'right meta', 'rm', 'right window key', 'rwk' ],
  93:   [ 'select' ],
  96:   [ 'numpad 0', 'num 0', 'n0' ],
  97:   [ 'numpad 1', 'num 1', 'n1' ],
  98:   [ 'numpad 2', 'num 2', 'n2' ],
  99:   [ 'numpad 3', 'num 3', 'n3' ],
  100:  [ 'numpad 4', 'num 4', 'n4' ],
  101:  [ 'numpad 5', 'num 5', 'n5' ],
  102:  [ 'numpad 6', 'num 6', 'n6' ],
  103:  [ 'numpad 7', 'num 7', 'n7' ],
  104:  [ 'numpad 8', 'num 8', 'n8' ],
  105:  [ 'numpad 9', 'num 9', 'n9' ],
  106:  [ 'multiply', 'star', 'asterisk', '*' ],
  107:  [ 'add', 'plus' ],
  109:  [ 'subtract', 'minus' ],
  110:  [ 'decimal', 'point' ],
  111:  [ 'divide' ],
  112:  [ 'f1' ],
  113:  [ 'f2' ],
  114:  [ 'f3' ],
  115:  [ 'f4' ],
  116:  [ 'f5' ],
  117:  [ 'f6' ],
  118:  [ 'f7' ],
  119:  [ 'f8' ],
  120:  [ 'f9' ],
  121:  [ 'f10' ],
  122:  [ 'f11' ],
  123:  [ 'f12' ],
  144:  [ 'num lock' ],
  145:  [ 'scroll lock' ],
  186:  [ 'semicolon', 'semi-colon' ],
  187:  [ 'equal', 'equal sign' ],
  188:  [ 'comma', ',' ],
  189:  [ 'dash', '-' ],
  190:  [ 'period', '.' ],
  191:  [ 'forward slash', '/' ],
  192:  [ 'grave accent', 'grave', '`' ],
  219:  [ 'open bracket', 'start bracket', 'starting bracket', '[' ],
  220:  [ 'backslash', 'back slash', '\\' ],
  221:  [ 'close bracket', 'end bracket', 'ending bracket', ']' ],
};